### ISSUE TITLE
dependencies in `package.json` seems to be an inconsistent state with `package-lock.json`

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill#2673]
(copied from slack)

ok, I've been thrashing around all afternoon trying to figure out what's going on with the shoelace package and why it doesn't seem to like working with storybook , and after trying a bunch of things I think i've determined that it has nothing to do with storybook, and that we actually have a long standing issue with the set of packages we're trying to use.

What I have just done most recently is

1. pull down a fresh copy of the repo, 
2. check out the commit directly before storybook mergerd
3. immediately delete package-lock.json
4. npm inatall
5. npm run dev

when I do this, I get the following error in the console:

```
Missing "./dist/internal/scroll" specifier in "@shoelace-style/shoelace" package
11:30:59 AM [vite] ✨ new dependencies optimized: @tanstack/svelte-query, yaml, ua-parser-js, @bufbuild/protobuf, crypto-js/md5, uuid, svelte-forms-lib, yup, @codemirror/autocomplete, @codemirror/commands, @codemirror/lang-sql, @codemirror/language, @codemirror/lint, @codemirror/search, @codemirror/state, @codemirror/view, d3-format, d3-array, d3-scale, d3-time-format, @tanstack/svelte-virtual, d3-interpolate-path, d3-scale-chromatic, d3-shape
11:30:59 AM [vite] ✨ optimized dependencies changed. reloading
2023-06-21T11:31:00.000-0700    INFO    Serving Rill on: http://localhost:9009
Missing "./dist/internal/scroll" specifier in "@shoelace-style/shoelace" package
11:31:08 AM [vite] Internal server error: Missing "./dist/internal/scroll" specifier in "@shoelace-style/shoelace" package
  Plugin: vite:import-analysis
  File: /home/bc/rill/rill-developer-burner/rill/web-common/src/components/modal/ModalContainer.svelte
      at e (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:25)
      at n (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:627)
      at o (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:16647:1297)
      at resolveExportsOrImports (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23405:20)
      at resolveDeepImport (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23424:31)
      at tryNodeResolve (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
      at Context.resolveId (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:32)
      at async TransformContext.resolve (file:///home/bc/rill/rill-developer-burner/rill/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23)
```

At this point, I'd be curious to hear from folks who have a deeper understanding of package resolution tangles like this, but also how the shoelace package is being used in particular because:

(a) It is my understanding that if our packages are in a consistent state, then deleting package lock and doing a fresh NPM install should not cause problems. Since our packages seem to not be in a consistent state, I'm not totally sure how to proceed. I can keep digging, but if someone has experience with this they might be able to clean things up more quickly than I can.

(b) shoelace seems to be kind of a special snowflake in that we import it within the on Mount of a component. In `web-common/src/components/modal/ModalContainer.svelte` we have:
```
  onMount(async () => {
    const scroll = await import(
      "@shoelace-style/shoelace/dist/internal/scroll"
    );
    lockBodyScrolling = scroll.lockBodyScrolling;
    unlockBodyScrolling = scroll.unlockBodyScrolling;
    Modal = (await import("@shoelace-style/shoelace/dist/internal/modal"))
      .default;
  });
```

@Hamilton Ulmer, it looks like you wrote this bit above -- do you happen to recall why this is needed? Any ideas as to how it might be interacting with this other set of problems?

**Comment by bcolloran** [comment]
(copied from slack for tracking)

@Hamilton Ulmer continuing to look into shoelace and what is going wrong with it when you try to create a fresh package-lock.json. I've tried moving the import out of that onMount  but the exact same error shows up:

Missing "./dist/internal/scroll" specifier in "@shoelace-style/shoelace" package
2023-06-22T11:43:19.825-0700    INFO    Serving Rill on: http://localhost:9009
11:43:22 AM [vite] Internal server error: Missing "./dist/internal/scroll" specifier in "@shoelace-style/shoelace" package
  Plugin: vite:import-analysis
  File: /home/bc/rill/rill-developer-burner/rill/web-common/src/components/modal/ModalContainer.svelte
...
-- so a file is not being found by vite

I'm not sure about this (bundlers are not something i have ever dug into) but it looks like shoelace is one of these newfangled libraries that is designed for CDN deliver rather than bundling. Looks like it wants special handling to work with npm install+bundling scenarios  https://shoelace.style/getting-started/installation#bundling.

What is really weird and puzzling to me about this is the interaction with package-lock.json , so there is some kind of crazy version conflict interaction here that I totally don't understand. The situation seems to be:
with the version package-lock.json on main, npm run dev works, but storybook breaks (so this file can apparently be found by vite+sveltekit with whatever set of module versions is specified by that package-lock, but not by the vite config used by storybook)
if you delete package-lock.json and recreate it by doing a fresh npm install, you get this error where the file cannot be found by the vite+sveltekit config used by npm run dev, but storybook works fine.

I think the fact that you cannot recreate a working repo from scratch with just package.json is a problem, and indicates the repo is brittle. Clearly it's causing problems now WRT adopting storybook.

I'm continuing to read articles and try stuff out, but I'm a bit at a loss. I think my next step will be to try upgrading a bunch of packages to see if that helps get us out of this tangle, but that is just my next shot in the dark. Would love suggestions. @Eric Green, I know you've worked on the svelte-kit setup a bunch, any ideas? @Speros Kokenes and @Aditya Hegde have you guys seen anything like this before?
